<?php
/**
 * An article: recipe, guide or topic page.
 *
 * Everything shown was computed at publish time — the contents, the internal
 * links, the reading time — so rendering is a handful of indexed reads.
 *
 * @var array  $article
 * @var array  $field
 * @var array  $ancestors
 * @var array  $toc
 * @var array  $recipe
 * @var array  $references
 * @var array  $related
 * @var array  $neighbours
 * @var array|null $hero
 * @var string $tocSide
 * @var bool   $showToc
 */

use App\Core\Url;
use App\Core\View;

?>
<div class="container article-layout" data-toc="<?= e($tocSide) ?>">

  <?php if ($showToc): ?>
  <aside class="article-sidebar">
    <button class="toc-toggle" type="button" data-toc-toggle aria-expanded="false" aria-controls="toc">
      فهرست مطالب
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <path d="m6 9 6 6 6-6"/>
      </svg>
    </button>

    <nav class="toc" id="toc" data-toc aria-label="فهرست مطالب">
      <p class="toc__title">فهرست مطالب</p>
      <?= View::render('partials.toc_list', ['items' => $toc]) ?>
    </nav>

    <?= View::render('partials.ad_slot', ['slot' => 'sidebar', 'fieldId' => (int) $field['id']]) ?>
  </aside>
  <?php endif; ?>

  <article class="article">
    <header class="article__header">
      <nav class="breadcrumbs" aria-label="مسیر">
        <a href="/">خانه</a>
        <?php foreach ($ancestors as $ancestor): ?>
          <span aria-hidden="true">/</span>
          <a href="<?= e(Url::field((string) $ancestor['path'])) ?>"><?= e($ancestor['title_fa']) ?></a>
        <?php endforeach; ?>
        <span aria-hidden="true">/</span>
        <a href="<?= e(Url::field((string) $field['path'])) ?>"><?= e($field['title_fa']) ?></a>
      </nav>

      <h1 class="article__title"><?= e($article['title_fa']) ?></h1>

      <div class="article__meta">
        <?php if ($article['kind'] === 'recipe'): ?>
          <span class="chip chip--accent">دستور پخت</span>
        <?php elseif ($article['kind'] === 'guide'): ?>
          <span class="chip chip--accent">راهنما</span>
        <?php endif; ?>
        <span class="chip"><?= e(fa((int) $article['reading_minutes'])) ?> دقیقه مطالعه</span>
        <?php if (!empty($article['published_at'])): ?>
          <span>به‌روزرسانی: <?= e(jalali((string) ($article['updated_at'] ?? $article['published_at']))) ?></span>
        <?php endif; ?>
        <?php if ($references !== []): ?>
          <span><a href="#references"><?= e(fa(count($references))) ?> منبع</a></span>
        <?php endif; ?>
      </div>
    </header>

    <?php if ($hero !== null && \App\Support\UrlGuard::isMediaPath($hero['path'] ?? null)): ?>
      <figure class="article__hero">
        <img src="/media/<?= e($hero['path']) ?>"
             alt="<?= e($hero['alt_fa'] ?? $article['title_fa']) ?>"
             width="<?= (int) ($hero['width'] ?: 1200) ?>"
             height="<?= (int) ($hero['height'] ?: 675) ?>">
        <figcaption>
          <span><?= e($hero['caption_fa'] ?? '') ?></span>
          <?php if (!empty($hero['is_ai_generated'])): ?>
            <?php /* Readers are told when an image was generated rather than
                     photographed. It costs nothing and it is the honest thing. */ ?>
            <span class="ai-badge">تصویر ساخته‌شده با هوش مصنوعی</span>
          <?php endif; ?>
        </figcaption>
      </figure>
    <?php endif; ?>

    <?= View::render('partials.ad_slot', ['slot' => 'article-top', 'fieldId' => (int) $field['id']]) ?>

    <?php if (!empty($article['summary_fa'])): ?>
      <p class="article__summary"><?= e($article['summary_fa']) ?></p>
    <?php endif; ?>

    <?php if ($article['kind'] === 'recipe' && $recipe !== []): ?>
      <?= View::render('partials.recipe_panel', ['recipe' => $recipe, 'article' => $article]) ?>
    <?php endif; ?>

    <?php /* body_html is generated by our own pipeline and sanitised at
             publish time, never taken raw from a submission. */ ?>
    <div class="prose"><?= $article['body_html'] ?></div>

    <?= View::render('partials.ad_slot', ['slot' => 'article-bottom', 'fieldId' => (int) $field['id']]) ?>

    <?php if ($references !== []): ?>
      <section class="article-section" id="references">
        <h2 class="article-section__title">منابع</h2>
        <ol class="references">
          <?php foreach ($references as $reference): ?>
            <li id="ref-<?= (int) $reference['marker'] ?>">
              <span class="references__marker"><?= e(fa((int) $reference['marker'])) ?>.</span>
              <span>
                <?php $refHref = \App\Support\UrlGuard::safeHref($reference['url']); ?>
                <?php if ($refHref !== null): ?>
                  <a class="references__title" href="<?= e($refHref) ?>" rel="nofollow noopener" target="_blank">
                    <?= e($reference['title'] ?: $refHref) ?>
                  </a>
                <?php else: ?>
                  <span class="references__title"><?= e($reference['title'] ?: '') ?></span>
                <?php endif; ?>
                <span class="references__source">
                  <?= e($reference['domain']) ?><?php
                    if (!empty($reference['author'])) { echo ' · ' . e($reference['author']); }
                    if (!empty($reference['published_date'])) { echo ' · ' . e((string) $reference['published_date']); }
                  ?>
                </span>
              </span>
            </li>
          <?php endforeach; ?>
        </ol>
      </section>
    <?php endif; ?>

    <?php if ($related !== []): ?>
      <section class="article-section">
        <h2 class="article-section__title">موضوعات مرتبط</h2>
        <div class="card-grid">
          <?php foreach ($related as $item): ?>
            <a class="card" href="<?= e(Url::article((string) $item['field_path'], (string) $item['slug'])) ?>">
              <span class="card__title"><?= e($item['title_fa']) ?></span>
              <?php if (!empty($item['summary_fa'])): ?>
                <span class="card__excerpt"><?= e(mb_substr(strip_tags((string) $item['summary_fa']), 0, 120, 'UTF-8')) ?></span>
              <?php endif; ?>
            </a>
          <?php endforeach; ?>
        </div>
      </section>
    <?php endif; ?>

    <?php if ($neighbours['previous'] || $neighbours['next']): ?>
      <nav class="neighbours" aria-label="نوشته‌های پیشین و پسین">
        <?php if ($neighbours['previous']): ?>
          <a href="<?= e(Url::article((string) $field['path'], (string) $neighbours['previous']['slug'])) ?>">
            <small>پیشین</small><?= e($neighbours['previous']['title_fa']) ?>
          </a>
        <?php endif; ?>
        <?php if ($neighbours['next']): ?>
          <a href="<?= e(Url::article((string) $field['path'], (string) $neighbours['next']['slug'])) ?>">
            <small>پسین</small><?= e($neighbours['next']['title_fa']) ?>
          </a>
        <?php endif; ?>
      </nav>
    <?php endif; ?>
  </article>
</div>
